# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KellyUI1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kelly(object):
    def setupUi(self, Kelly):
        Kelly.setObjectName("Kelly")
        Kelly.resize(941, 559)
        self.Bg_1 = QtWidgets.QLabel(Kelly)
        self.Bg_1.setGeometry(QtCore.QRect(-4, 2, 1101, 591))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/Black_Template.jpg"))
        self.Bg_1.setObjectName("Bg_1")
        self.Gif_1 = QtWidgets.QLabel(Kelly)
        self.Gif_1.setGeometry(QtCore.QRect(60, 90, 561, 331))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("G.U.I Material/VoiceReg/Siri_1.gif"))
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(Kelly)
        self.Gif_2.setGeometry(QtCore.QRect(0, 330, 391, 261))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/Earth_Template.gif"))
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(Kelly)
        self.Gif_3.setGeometry(QtCore.QRect(0, -60, 311, 291))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/Code_Template.gif"))
        self.Gif_3.setObjectName("Gif_3")
        self.Gif_4 = QtWidgets.QLabel(Kelly)
        self.Gif_4.setGeometry(QtCore.QRect(540, 0, 421, 141))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/initial.gif"))
        self.Gif_4.setObjectName("Gif_4")
        self.Gif_5 = QtWidgets.QLabel(Kelly)
        self.Gif_5.setGeometry(QtCore.QRect(620, 370, 311, 181))
        self.Gif_5.setText("")
        self.Gif_5.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/B.G_Template_1.gif"))
        self.Gif_5.setObjectName("Gif_5")
        self.pushButton_stop = QtWidgets.QPushButton(Kelly)
        self.pushButton_stop.setGeometry(QtCore.QRect(320, 510, 101, 31))
        self.pushButton_stop.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_yt = QtWidgets.QPushButton(Kelly)
        self.pushButton_yt.setGeometry(QtCore.QRect(840, 120, 101, 31))
        self.pushButton_yt.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_yt.setObjectName("pushButton_yt")
        self.pushButton_whatsapp = QtWidgets.QPushButton(Kelly)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(840, 160, 101, 31))
        self.pushButton_whatsapp.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        self.pushButton_fb = QtWidgets.QPushButton(Kelly)
        self.pushButton_fb.setGeometry(QtCore.QRect(840, 190, 101, 31))
        self.pushButton_fb.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_fb.setObjectName("pushButton_fb")
        self.pushButton_snap = QtWidgets.QPushButton(Kelly)
        self.pushButton_snap.setGeometry(QtCore.QRect(840, 220, 101, 31))
        self.pushButton_snap.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_snap.setObjectName("pushButton_snap")
        self.pushButton_chrome = QtWidgets.QPushButton(Kelly)
        self.pushButton_chrome.setGeometry(QtCore.QRect(840, 260, 101, 31))
        self.pushButton_chrome.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.pushButton_start = QtWidgets.QPushButton(Kelly)
        self.pushButton_start.setGeometry(QtCore.QRect(450, 510, 101, 31))
        self.pushButton_start.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"\n"
"border-color: rgb(0, 0, 127);")
        self.pushButton_start.setObjectName("pushButton_start")

        self.retranslateUi(Kelly)
        QtCore.QMetaObject.connectSlotsByName(Kelly)

    def retranslateUi(self, Kelly):
        _translate = QtCore.QCoreApplication.translate
        Kelly.setWindowTitle(_translate("Kelly", "Dialog"))
        self.pushButton_stop.setText(_translate("Kelly", "Stop"))
        self.pushButton_yt.setText(_translate("Kelly", "YouTube"))
        self.pushButton_whatsapp.setText(_translate("Kelly", "Whatsapp"))
        self.pushButton_fb.setText(_translate("Kelly", "Facebook"))
        self.pushButton_snap.setText(_translate("Kelly", "Snapchat"))
        self.pushButton_chrome.setText(_translate("Kelly", "Chrome"))
        self.pushButton_start.setText(_translate("Kelly", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kelly = QtWidgets.QDialog()
    ui = Ui_Kelly()
    ui.setupUi(Kelly)
    Kelly.show()
    sys.exit(app.exec_())
